#define ID 0
#define AEROLINEA 1 
#define ORIGEN 2
#define DESTINO 3
#define NUMERO_DE_COLA 4
#define PRIORIDAD 5
#define FECHA 6
#define RETRASO 7
#define TIEMPO_DE_VUELO 8
#define CANCELADO 9

#define EOF (-1)

#define CANTIDAD_PARAMETROS_AGREGAR_ARCHIVO 1
#define CANTIDAD_PARAMETROS_INFO_VUELO 1
#define CANTIDAD_PARAMETROS_PRIORIDADES 1

